<?php
/**
 * @file
 * Another crazy idea.
 */

/**
 * Implements hook_menu().
 */
function easy_visitor_stats_menu() {
  // Collect data via AJAX post:
  $items['easy-visitor-stats'] = array(
    'title' => 'Stats get',
    'page callback' => '_easy_visitor_stats_ajax_endpoint',
    'delivery callback' => '_easy_visitor_stats_no_content',
    'access callback' => TRUE,
  );
  // Dynamically fetch chart data for report via AJAX post:
  $items['easy-visitor-stats-fetch/history'] = array(
    'title' => 'Stats data',
    'page callback' => '_easy_visitor_stats_ajax_history',
    'delivery callback' => 'backdrop_json_deliver',
    'access arguments' => array('access statistics dashboard'),
  );
  $items['easy-visitor-stats-fetch/hits'] = array(
    'title' => 'Stats data',
    'page callback' => '_easy_visitor_stats_ajax_hits',
    'delivery callback' => 'backdrop_json_deliver',
    'access arguments' => array('access statistics dashboard'),
  );
  // Pages.
  $items['admin/reports/easy-visitor-stats'] = array(
    'title' => 'Easy Visitor Statistics',
    'page callback' => '_easy_visitor_stats_dashboard',
    'access arguments' => array('access statistics dashboard'),
    'file' => 'easy_visitor_stats.pages.inc',
  );
  $items['admin/reports/easy-visitor-stats/dashboard'] = array(
    'title' => 'Dashboard',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/reports/easy-visitor-stats/raw-data'] = array(
    'title' => 'Raw data',
    'type' => MENU_LOCAL_TASK,
    'page callback' => '_easy_visitor_stats_raw',
    'access arguments' => array('access statistics raw data'),
    'file' => 'easy_visitor_stats.pages.inc',
  );
  $items['admin/reports/easy-visitor-stats/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('_easy_visitor_stats_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'easy_visitor_stats.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function easy_visitor_stats_theme($existing, $type, $theme, $path) {
  $module_path = backdrop_get_path('module', 'easy_visitor_stats');
  $items = array(
    'easy_visitor_stats_dashboard' => array(
      'file' => 'theme/easy_visitor_stats.theme.inc',
      'template' => 'theme/easy-visitor-stats-dashboard',
      'attached' => array(
        'js' => array(
          $module_path . '/libraries/chart.umd.min.js',
          $module_path . '/js/easy-visitor-charts.js',
        ),
        'css' => array(
          $module_path . '/css/easy-visitor-stats-chart.css',
        ),
      ),
      'variables' => array(
        'infotext' => '',
        'total_page_hits' => 0,
        'average_time_spent' => '0.00s',
        'hits_select' => '',
        'history_select' => '',
        'top_ten' => '',
      ),
    ),
  );
  return $items;
}

/**
 * Page callback
 */
function _easy_visitor_stats_ajax_endpoint() {
  if (state_get('maintenance_mode', FALSE) || empty($_POST)) {
    return;
  }
  if (empty($_POST['href'])) {
    return;
  }
  $href_host = parse_url($_POST['href'], PHP_URL_HOST);
  // Filter out garbage data.
  if (empty($href_host) || !backdrop_check_trusted_hosts($href_host)) {
    return;
  }
  if (!empty($_POST['ua']) && _easy_visitor_stats_detect_bot($_POST['ua'])) {
    return;
  }
  // There should have been a GET before this POST.
  $site_key = state_get('easyVisitorStatsSiteKey');
  if ($site_key && (empty($_POST['siteKey']) || $_POST['siteKey'] != $site_key)) {
    return;
  }

  $collection = array(
    'href' => '',
    'duration' => 0,
    'timezone' => '',
    'referrer' => '',
  );
  foreach ($collection as $key => $value) {
    if (isset($_POST[$key])) {
      switch ($key) {
        case 'duration':
          $collection[$key] = (int) $_POST[$key];
          break;

        case 'href':
          global $base_url;
          $href = filter_xss($_POST[$key]);
          if (strpos($href, $base_url) === 0) {
            $local_url = substr($href, strlen($base_url));
            $collection[$key] = substr($local_url, 0, 2048);
          }
          break;

        case 'referrer':
          $collection[$key] = substr(filter_xss($_POST[$key]), 0, 2048);
          break;

        default:
          $collection[$key] = filter_xss($_POST[$key]);
      }
    }
  }

  $os_browser = _easy_visitor_stats_guess_os_browser($_POST);
  $collection['os'] = $os_browser['os'];
  $collection['browser'] = $os_browser['browser'];

  // Server side info.
  $collection['timestamp'] = REQUEST_TIME;
  $collection['ip'] = _easy_visitor_stats_ip_address();

  $query = db_insert('easy_visitor_details')->fields(array(
    'href', 'duration', 'timezone', 'referrer',
    'os', 'browser', 'timestamp', 'ip',
  ));
  $query->values($collection);
  $query->execute();

  // Increment page hits, create value if necessary.
  $date_today = format_date(REQUEST_TIME, 'custom', 'Y-m-d');
  db_query('INSERT INTO {easy_visitor_history} VALUES(' . "'" . $date_today . "',1" . ') ON DUPLICATE KEY UPDATE hits=hits+1;');
}

/**
 * Custom delivery callback for AJAX endpoint.
 */
function _easy_visitor_stats_no_content() {
  // According to w3.org:
  // "The server is encouraged to omit returning a response body for such
  // requests (sendBeacon)."
  backdrop_add_http_header('Status', '204 No Content');// seems to return 200 though...
}

/**
 * Guess if this is a bot by patterns.
 *
 * It's unclear, how many of those bots actually execute JavaScript.
 */
function _easy_visitor_stats_detect_bot($ua_string) {
  $pattern1 = '#Mozilla/\d\.0 \(compatible; ?[A-Za-z0-9]+(b|B)ot[;/]#';
  if (preg_match($pattern1, $ua_string) === 1) {
    return TRUE;
  }
  $pattern_2 = '/(SearchBot|ClaudeBot|Bytespider|facebookexternalhit|Exabot|WebIndex|Applebot|SleepBot|bingbot|Go-http-client|DuckAssistBot|Barkrowler|Sogou|Baiduspider|Googlebot|HeadlessChrome)/';
  if (preg_match($pattern_2, $ua_string) === 1) {
    return TRUE;
  }
  // It may still be a bot, but in disguise.
  return FALSE;
}

/**
 * Guess OS and browser.
 */
function _easy_visitor_stats_guess_os_browser($post) {
  $info = array(
    'os' => '',
    'browser' => '',
  );
  if (empty($post['platform']) && empty($post['ua'])) {
    return $info;
  }

  if (!empty($post['ua'])) {
    $ua = filter_xss($post['ua']);
    $platform = !empty($post['platform']) ? filter_xss($post['platform']) : '';
    if (strpos($platform, 'Win') === 0) {
      $info['os'] = 'Windows';
    }
    elseif (strpos($platform, 'Linux') === 0) {
      if (strpos($ua, 'Android') > 0) {
        $info['os'] = 'Android';
      }
      else {
        $info['os'] = 'Linux';
      }
    }
    else {
      $info['os'] = $platform;
    }

    // Order matters!
    if (preg_match('/Mozilla.+Chrome.+Safari/', $ua) == 1) {
      $info['browser'] = 'Chrome';
    }
    elseif (preg_match('/Mozilla.+AppleWebKit.+Safari/', $ua) == 1) {
      $info['browser'] = 'Safari';
    }
    elseif (preg_match('/Mozilla.+Gecko.+Firefox/', $ua) == 1) {
      $info['browser'] = 'Firefox';
    }
    else {
      // Too many different to bother.
      $info['browser'] = 'other';
    }
  }
  return $info;
}

/**
 * Strip off the last octet to comply with privacy requirements.
 */
function _easy_visitor_stats_ip_address() {
  $ip = ip_address();
  $ipv4_netmask = '255.255.255.0';
  $ipv6_netmask = 'ffff:ffff:ffff:ffff:0000:0000:0000:0000';
  if (strpos($ip, ':') === FALSE) {
    return inet_ntop(inet_pton($ip) & inet_pton($ipv4_netmask));
  }
  else {
    return inet_ntop(inet_pton($ip) & inet_pton($ipv6_netmask));
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function easy_visitor_stats_preprocess_page($variables) {
  global $user;
  $status = backdrop_get_http_header('Status');
  if ($status == '404 Not Found' || $status == '403 Forbidden') {
    return;
  }
  // Only anonymous.
  if (!$user->uid) {
    $site_key = state_get('easyVisitorStatsSiteKey', FALSE);
    backdrop_add_js(backdrop_get_path('module', 'easy_visitor_stats') . '/js/easy-visitor-stats.js');
    backdrop_add_js(array(
      'easyVisitorStatsSiteKey' => $site_key,
      'easyVisitorStatsBeaconUrl' => base_path() . 'easy-visitor-stats',
    ), 'setting');
  }
}

/**
 * Implements hook_cron().
 */
function easy_visitor_stats_cron() {
  $config = config('easy_visitor_stats.settings');
  $details_old_date = new DateTime($config->get('keep_detailed_days') . ' days ago');
  $history_old_date = new DateTime($config->get('keep_history_months') . ' months ago');
  db_delete('easy_visitor_details')
    ->condition('timestamp', $details_old_date->format('U'), '<')
    ->execute();
  db_delete('easy_visitor_history')
    ->condition('date', $history_old_date->format('Y-m-d'), '<')
    ->execute();
}

/**
 * Implements hook_permission().
 */
function easy_visitor_stats_permission() {
  $permissions = array(
    'access statistics dashboard' => array(
      'title' => t('Access dashboard'),
      'description' => t('Access Easy Visitor Statistics dashboard.'),
    ),
    'access statistics raw data' => array(
      'title' => t('Access raw data'),
      'description' => t('Access Easy Visitor Statistics raw data table.'),
    ),
  );
  return $permissions;
}

/**
 * Implements hook_config_info().
 */
function easy_visitor_stats_config_info() {
  $prefixes['easy_visitor_stats.settings'] = array(
    'label' => t('Easy Visitor Stats Settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * AJAX endpoint for easy-visitor-stats-fetch/history.
 */
function _easy_visitor_stats_ajax_history() {
  $args = arg();
  $date_pattern = '/^\d{4}-\d{2}-\d{2}$/';
  if (count($args) != 4 || preg_match($date_pattern, $args[2]) != 1 || preg_match($date_pattern, $args[3]) != 1) {
    backdrop_not_found();
    return;
  }

  $start = $args[2];
  $end = $args[3];
  $data = db_query("SELECT * FROM {easy_visitor_history} WHERE date >= :start and date <= :end", array(
    ':start' => $start,
    ':end' => $end,
  ))->fetchAll();
  $history_hits = array();
  foreach ($data as $record) {
    $history_hits[$record->date] = (int) $record->hits;
  }

  $range_begin = DateTime::createFromFormat('Y-m-d', $start);
  $range_end = DateTime::createFromFormat('Y-m-d', $end);
  if (!$range_begin || !$range_end || $range_begin > $range_end) {
    backdrop_not_found();
  }
  $day_ranges = array($start => 0);
  while($range_begin < $range_end) {
    $range_begin->modify('+1 day');
    $key = $range_begin->format('Y-m-d');
    $day_ranges[$key] = 0;
  }
  $merged_data = array_merge($day_ranges, $history_hits);
  $chart_data = array(
    'labels' => array_keys($merged_data),
    'values' => array_values($merged_data),
  );

  return $chart_data;
}

/**
 * AJAX endpoint for easy-visitor-stats-fetch/hits.
 */
function _easy_visitor_stats_ajax_hits() {
  $args = arg();
  $arg_pattern = '/^\d+$/';
  if (count($args) != 4 || preg_match($arg_pattern, $args[2]) != 1 || preg_match($arg_pattern, $args[3]) != 1) {
    backdrop_not_found();
    return;
  }

  $start = (int) $args[2];
  $end = (int) $args[3];
  $max_range_size = 3600 * 24 * 30;
  // Filter out garbage just in case.
  if ($start > $end || $end - $start > $max_range_size) {
    backdrop_not_found();
    return;
  }
  // Hits based on hourly data.
  $data = db_query("SELECT timestamp FROM {easy_visitor_details} WHERE timestamp >= :start AND timestamp <= :end", array(
    ':start' => $start,
    ':end' => $end,
  ))->fetchAllAssoc('timestamp');
  $timestamps = array_keys($data);

  $site_timezone = new DateTimeZone(config_get('system.date','default_timezone'));
  $start_date = new DateTime('@' . $start);
  $start_date->setTimezone($site_timezone);
  $end_date = new dateTime('@' . $end);
  $end_date->setTimezone($site_timezone);

  $hour_ranges = array();
  while($start_date < $end_date) {
    $start_date->modify('+1 hour');
    $key = $start_date->format('Y-m-d H');
    $hour_ranges[$key] = 0;
  }
  $hits = array();
  foreach ($timestamps as $timestamp) {
    $date = format_date($timestamp, 'custom', 'Y-m-d H');
    if (array_key_exists($date, $hits)) {
      $hits[$date] = $hits[$date] + 1;
    }
    else {
      $hits[$date] = 1;
    }
  }
  $merged_data = array_merge($hour_ranges, $hits);
  $chart_data = array(
    'labels' => array_keys($merged_data),
    'values' => array_values($merged_data),
  );

  return $chart_data;
}
