<?php
/**
 * @file
 * Another crazy idea.
 */

/**
 * Implements hook_menu().
 */
function easy_visitor_stats_menu() {
  $items['easy-visitor-stats'] = array(
    'title' => 'Stats get',
    'page callback' => '_easy_visitor_stats_ajax_endpoint',
    'delivery callback' => '_easy_visitor_stats_no_content',
    'access callback' => TRUE,
  );
  $items['admin/reports/easy-visitor-stats'] = array(
    'title' => 'Easy Visitor Statistics',
    'page callback' => '_easy_visitor_stats_dashboard',
    'access arguments' => array('administer site configuration'),// @todo custom perm
    'file' => 'easy_visitor_stats.pages.inc',
  );
  $items['admin/reports/easy-visitor-stats/dashboard'] = array(
    'title' => 'Dashboard',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  // @todo hook_config_info, permission...
  $items['admin/reports/easy-visitor-stats/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('_easy_visitor_stats_settings_form'),
    'access arguments' => array('administer site configuration'),// @todo custom perm
    'file' => 'easy_visitor_stats.pages.inc',
  );

  // also need admin pages and perms (view, configure), possibly a block... something to attach to nodes?
  return $items;
}

/**
 * Page callback
 */
function _easy_visitor_stats_ajax_endpoint() {
  if (state_get('maintenance_mode', FALSE) || empty($_POST)) {
    return;
  }
  if (empty($_POST['href'])) {
    return;
  }
  // @todo some sort of token (get before post) might be tricky
  $href_host = parse_url($_POST['href'], PHP_URL_HOST);
  // Filter out garbage data.
  if (empty($href_host) || !backdrop_check_trusted_hosts($href_host)) {
    return;
  }
  if (!empty($_POST['ua']) && _easy_visitor_stats_detect_bot($_POST['ua'])) {
    return;
  }
  $collection = array(
    'href' => '',
    'duration' => 0,
    'timezone' => '',
    'referrer' => '',
  );
  // @todo db field for href and referrer: 'length' => 2048,
  foreach ($collection as $key => $value) {
    if (isset($_POST[$key])) {
      switch ($key) {
        case 'duration':
          $collection[$key] = (int) $_POST[$key];
          break;

        case 'href':
          global $base_url;
          $href = filter_xss($_POST[$key]);
          if (strpos($href, $base_url) === 0) {
            $local_url = substr($href, strlen($base_url));
            $collection[$key] = substr($local_url, 0, 2048);
          }
          break;

        case 'referrer':
          $collection[$key] = substr(filter_xss($_POST[$key]), 0, 2048);
          break;

        default:
          $collection[$key] = filter_xss($_POST[$key]);
      }
    }
  }

  $os_browser = _easy_visitor_stats_guess_os_browser($_POST);
  $collection['os'] = $os_browser['os'];
  $collection['browser'] = $os_browser['browser'];

  // Server side info.
  $collection['timestamp'] = REQUEST_TIME;
  $collection['ip'] = _easy_visitor_stats_ip_address();

  $query = db_insert('easy_visitor_details')->fields(array(
    'href', 'duration', 'timezone', 'referrer',
    'os', 'browser', 'timestamp', 'ip',
  ));
  $query->values($collection);
  $query->execute();

  // Increment page hits, create value if necessary.
  $date_today = format_date(REQUEST_TIME, 'custom', 'Y-m-d');
  db_query('INSERT INTO {easy_visitor_history} VALUES(' . "'" . $date_today . "',1" . ') ON DUPLICATE KEY UPDATE hits=hits+1;');
}

/**
 * Custom delivery callback for AJAX endpoint.
 */
function _easy_visitor_stats_no_content() {
  // @todo header noarchive, nobla...

  // According to w3.org:
  // "The server is encouraged to omit returning a response body for such
  // requests (sendBeacon)."
  backdrop_add_http_header('Status', '204 No Content');// seems to return 200 though...
}

/**
 * Guess if this is a bot by patterns.
 *
 * It's unclear, how many of those bots actually execute JavaScript.
 */
function _easy_visitor_stats_detect_bot($ua_string) {
  $pattern1 = '#Mozilla/\d\.0 \(compatible; ?[A-Za-z0-9]+(b|B)ot[;/]#';
  if (preg_match($pattern1, $ua_string) === 1) {
    return TRUE;
  }
  $pattern_2 = '/(SearchBot|ClaudeBot|Bytespider|facebookexternalhit|Exabot|WebIndex|Applebot|SleepBot|bingbot|Go-http-client|DuckAssistBot|Barkrowler|Sogou|Baiduspider|Googlebot)/';
  if (preg_match($pattern_2, $ua_string) === 1) {
    return TRUE;
  }
  // It may still be a bot, but in disguise.
  return FALSE;
}

/**
 * Guess OS and browser.
 */
function _easy_visitor_stats_guess_os_browser($post) {
  $info = array(
    'os' => '',
    'browser' => '',
  );
  if (empty($post['platform']) && empty($post['ua'])) {
    return $info;
  }

  if (!empty($post['ua'])) {
    $ua = filter_xss($post['ua']);
    $platform = !empty($post['platform']) ? filter_xss($post['platform']) : '';
    if (strpos($platform, 'Win') === 0) {
      $info['os'] = 'Windows';
    }
    elseif (strpos($platform, 'Linux') === 0) {
      if (strpos($ua, 'Android') > 0) {
        $info['os'] = 'Android';
      }
      else {
        $info['os'] = 'Linux';
      }
    }
    else {
      $info['os'] = $platform;
    }

    // Order matters!
    if (preg_match('/Mozilla.+Chrome.+Safari/', $ua) == 1) {
      $info['browser'] = 'Chrome';
    }
    elseif (preg_match('/Mozilla.+AppleWebKit.+Safari/', $ua) == 1) {
      $info['browser'] = 'Safari';
    }
    elseif (preg_match('/Mozilla.+Gecko.+Firefox/', $ua) == 1) {
      $info['browser'] = 'Firefox';
    }
    else {
      // Too many different to bother.
      $info['browser'] = 'other';
    }
  }
  return $info;
}

/**
 * Strip off the last octet to comply with privacy requirements.
 */
function _easy_visitor_stats_ip_address() {
  $ip = ip_address();
  $ipv4_netmask = '255.255.255.0';
  $ipv6_netmask = 'ffff:ffff:ffff:ffff:0000:0000:0000:0000';
  if (strpos($ip, ':') === FALSE) {
    return inet_ntop(inet_pton($ip) & inet_pton($ipv4_netmask));
  }
  else {
    return inet_ntop(inet_pton($ip) & inet_pton($ipv6_netmask));
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function easy_visitor_stats_preprocess_page($variables) {
  global $user;
  if (!$user->uid) {// only anonymous? the module name is "... visitor ... " ;-) or by role and configurable?
    // Aggregation does not seem to matter.
    backdrop_add_js(backdrop_get_path('module', 'easy_visitor_stats') . '/js/easy-visitor-stats.js');
  }
}
